import {notFound} from 'next/navigation';import {q} from '@/lib/db';import {need} from '@/lib/auth';import Shell from '@/components/Shell';import WOView from '@/components/WOView';
import {buildGantt} from '@/lib/gantt';import {cal,visible,summarize,woClocks,taskClock,remaining,evidence,ACT} from '@/lib/wo';import {teamList,partyList} from '@/lib/lists';
export const dynamic='force-dynamic';
export default async function P({params}){const u=await need(),id=+params.id;if(!id||!(await visible(u,id)))notFound();await cal();
 const wo=(await q('select w.*,u.name creator from work_orders w left join users u on u.id=w.created_by where w.id=$1',[id]))[0];if(!wo)notFound();
 const tasks=await q('select * from tasks where wo_id=$1 order by seq',[id]),spans=await q('select task_id,state,party,t_start,t_end from task_spans where wo_id=$1',[id]);
 const ev=await q(`select e.id,e.task_id,e.at,e.user_name,e.action,e.comment,coalesce((select json_agg(json_build_object('id',a.id,'name',a.name,'size',a.size)) from attachments a where a.event_id=e.id),'[]'::json) files from task_events e where e.wo_id=$1 order by e.at desc,e.id desc limit 200`,[id]);
 const docs=await q("select id,num,type,status,data->>'fin' fin from docs where wo_id=$1 order by id",[id]),assets=await q('select a.* from assets a join wo_assets x on x.asset_id=a.id where x.wo_id=$1',[id]),users=await q('select id,name,team,role from users order by name'),subs=await q('select * from subtasks where wo_id=$1 order by pos,id',[id]),apps=await q('select id,task_id,title,status,client_name,comment,viewed_at,decided_at,token from approvals where wo_id=$1 order by id',[id]),allFiles=await q('select id,name,task_id from attachments where wo_id=$1 order by id',[id]),cinfo=wo.client_id?((await q('select email,phone from clients where id=$1',[wo.client_id]))[0]||{}):{};
 const now=Date.now(),S=summarize(wo,tasks,now,subs),G=buildGantt(wo,tasks,spans,now),C=woClocks(wo,tasks,spans,now),teams=await teamList(),parties=await partyList();
 const T=await Promise.all(tasks.map(async t=>({...t,subs:subs.filter(s=>s.task_id===t.id),approvals:apps.filter(a=>a.task_id===t.id),clock:taskClock(t,spans,now),rem:remaining(t,now),waited:now-+new Date(t.state_since),missing:ACT.includes(t.status)?await evidence(t):[],blockedBy:t.status==='blocked'?tasks.filter(x=>t.depends.includes(x.id)&&!['done','skipped'].includes(x.status)).map(x=>x.title):[]})));
 const J=x=>JSON.parse(JSON.stringify(x));
 return <Shell u={u}><WOView wo={J(wo)} S={J(S)} C={J(C)} T={J(T)} ev={J(ev)} docs={J(docs)} assets={J(assets)} users={J(users)} sups={J(users.filter(x=>['admin','supervisor'].includes(x.role)))} G={J(G)} allFiles={J(allFiles)} cinfo={J(cinfo)} teams={J(teams)} parties={J(parties)} me={{id:u.id,role:u.role,team:u.team}}/></Shell>}
