import Link from 'next/link';import {q} from '@/lib/db';import {need} from '@/lib/auth';import Shell from '@/components/Shell';import {loadWOs,FILTERS} from '@/lib/wolist';import {dur} from '@/lib/time';
export const dynamic='force-dynamic';
export default async function Home(){const u=await need();const rows=await loadWOs(u,{st:'open'});
 const tech=u.role==='tech',args=tech?[u.id,u.team||'Technical']:[];
 const done=Object.fromEntries((await q(`select status,count(*)::int n from work_orders w where status in ('completed','closed') ${tech?'and (w.created_by=$1 or exists(select 1 from tasks t where t.wo_id=w.id and (t.assignee=$1 or t.team=$2)) or exists(select 1 from subtasks s where s.wo_id=w.id and s.assignee=$1))':''} group by status`,args)).map(x=>[x.status,x.n]));
 const B={};rows.forEach(w=>{if(!w.S.p)return;const b=B[w.S.bucket]||(B[w.S.bucket]={n:0,ms:0});b.n++;b.ms+=w.S.waited});
 const buckets=Object.entries(B).sort((a,b)=>b[1].ms-a[1].ms);
 const mine=await q(`select t.id,t.title,t.status,t.team,t.due_at,t.wo_id,w.num,w.client from tasks t join work_orders w on w.id=t.wo_id where w.status='open' and t.status in ('ready','assigned','accepted','in_progress','waiting') and (t.assignee=$1 or (t.assignee is null and t.team=$2)) order by t.state_since limit 30`,[u.id,u.team||'Technical']);
 const sv=u.role==='tech'?[]:await q(`select t.id,t.title,t.status,t.team,t.assignee_name,t.due_at,t.wo_id,w.num,w.client from tasks t join work_orders w on w.id=t.wo_id where w.status='open' and t.supervisor=$1 and t.status in ('ready','assigned','accepted','in_progress','waiting') order by t.state_since limit 30`,[u.id]);
 const mySubs=await q(`select s.id,s.title,s.status,s.wo_id,w.num,w.client,t.title task from subtasks s join tasks t on t.id=s.task_id join work_orders w on w.id=s.wo_id where w.status='open' and s.status<>'done' and s.assignee=$1 order by s.id limit 30`,[u.id]);
 const T=Object.entries(FILTERS).map(([k,[l,f]])=>[k,l,rows.filter(w=>f(w.S)).length]);
 return <Shell u={u}><div className="row"><h2 style={{margin:0}}>Control tower</h2><span className="grow"/><Link className="btn p" href="/workorders/new">+ New work order</Link></div>
  <div className="row" style={{margin:'12px 0',alignItems:'stretch'}}>{T.map(([k,l,n])=><div className={'card stat'+(k==='overdue'&&n?' bad':'')} key={k}><Link href={'/workorders?f='+k}><div className="mut">{l}</div><div className="n">{n}</div></Link></div>)}
   <div className="card stat"><Link href="/workorders?st=completed"><div className="mut">Completed</div><div className="n">{done.completed||0}</div></Link></div><div className="card stat"><Link href="/workorders?st=closed"><div className="mut">Closed</div><div className="n">{done.closed||0}</div></Link></div></div>
  <h3>Where are jobs stuck?</h3><table className="list" style={{marginBottom:16}}><thead><tr><th>Waiting on / owner</th><th>Jobs</th><th>Total waiting</th></tr></thead><tbody>
  {buckets.map(([b,x])=><tr key={b}><td><Link href={'/workorders?b='+encodeURIComponent(b)}>{b}</Link></td><td>{x.n}</td><td>{dur(x.ms)}</td></tr>)}{!buckets.length&&<tr><td colSpan={3} className="mut">No open work orders.</td></tr>}</tbody></table>
  <h3>My work</h3><table className="list"><thead><tr><th>Work order</th><th>Task</th><th>Status</th><th>Due</th></tr></thead><tbody>
  {mine.map(t=><tr key={t.id}><td><Link href={'/workorders/'+t.wo_id}>{t.num}</Link> <span className="mut">{t.client}</span></td><td>{t.title}</td><td><span className={'badge '+t.status}>{t.status.replace('_',' ')}</span></td><td className="mut">{t.due_at?new Date(t.due_at).toLocaleString():'—'}</td></tr>)}{!mine.length&&<tr><td colSpan={4} className="mut">Nothing waiting on you or your team.</td></tr>}</tbody></table>
  {mySubs.length>0&&<><h3>My sub-tasks</h3><table className="list"><thead><tr><th>Work order</th><th>Sub-task</th><th>Part of</th><th>Status</th></tr></thead><tbody>{mySubs.map(x=><tr key={x.id}><td><Link href={'/workorders/'+x.wo_id}>{x.num}</Link> <span className="mut">{x.client}</span></td><td>{x.title}</td><td>{x.task}</td><td><span className={'badge '+(x.status==='in_progress'?'in_progress':'blocked')}>{x.status==='todo'?'to do':'in progress'}</span></td></tr>)}</tbody></table></>}
  {sv.length>0&&<><h3>Supervising</h3><table className="list"><thead><tr><th>Work order</th><th>Task</th><th>Owner</th><th>Status</th><th>Due</th></tr></thead><tbody>{sv.map(t=><tr key={t.id}><td><Link href={'/workorders/'+t.wo_id}>{t.num}</Link> <span className="mut">{t.client}</span></td><td>{t.title}</td><td>{t.assignee_name||t.team}</td><td><span className={'badge '+t.status}>{t.status.replace('_',' ')}</span></td><td className="mut">{t.due_at?new Date(t.due_at).toLocaleString():'—'}</td></tr>)}</tbody></table></>}</Shell>}
