'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';
function Ed({t}){const r=useRouter(),[f,setF]=useState(t),[m,setM]=useState('');
 const save=async()=>{setM('');const x=await fetch('/api/templates',{method:'POST',body:JSON.stringify(f)}),j=await x.json();if(!x.ok)return setM(j.error);setM('Saved ✓');if(!t.id){setF({name:'',service:'',dsl:'',active:true})}r.refresh()};
 return <details className="card" open={!t.id}><summary><b>{t.id?t.name:'+ New template'}</b> <span className="mut">{t.service}</span>{t.id&&!t.active&&<span className="badge draft" style={{marginLeft:8}}>hidden</span>}</summary>
  <div className="row" style={{margin:'10px 0'}}><input placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Group (e.g. Installation)" value={f.service||''} onChange={e=>setF({...f,service:e.target.value})}/><label><input type="checkbox" style={{width:'auto'}} checked={f.active!==false} onChange={e=>setF({...f,active:e.target.checked})}/> Active</label></div>
  <textarea className="mono" rows={14} style={{border:'1px solid var(--line)',borderRadius:8,padding:8,fieldSizing:'fixed'}} value={f.dsl} onChange={e=>setF({...f,dsl:e.target.value})}/>
  {m&&<p className={m==='Saved ✓'?'':'err'} style={{whiteSpace:'pre-wrap'}}>{m}</p>}<p><button className="btn p" onClick={save}>Save template</button></p></details>}
export default function TemplateAdmin({items}){return <>
 <div className="card"><b>Format</b> — one task per line:<br/><span className="mono">key | Title | Team | Duration | depends-on keys | options</span>
  <p className="mut" style={{marginBottom:0}}>Teams: SM Sales &amp; Marketing · TS Technical Sales · PR Procurement · TE Technical · SD Software Development · SU Support · SV Supervisor · MG Management. Duration: 30m, 6h or 2d (a day = 9 working hours). Dependencies must be earlier keys, comma separated. Options, separated by ; : <span className="mono">wait=Client</span> (auto-waits on that party) · <span className="mono">why=client approval</span> · <span className="mono">ev=fileref+check+doc+signed</span> (evidence needed to complete) · <span className="mono">chk=Step one~Step two</span> or <span className="mono">chk=@items</span> · <span className="mono">doc=sr:Site Survey</span> (field document; also wt: or ho:) · <span className="mono">opt</span> (optional) · <span className="mono">next=text</span>. Existing work orders keep the workflow they were created with.</p></div>
 <Ed t={{name:'',service:'',dsl:'',active:true}}/>{items.map(t=><Ed key={t.id} t={t}/>)}</>}
