import {q} from './db';import {cal,summarize} from './wo';
export const FILTERS={open:['Open',()=>true],today:['Due today',s=>s.dueToday],overdue:['Overdue',s=>s.overdue],accept:['Awaiting acceptance',s=>s.status==='assigned'],approval:['Awaiting approval',s=>s.status==='pending_approval'],client:['Awaiting client',s=>s.bucket==='Client'],supplier:['Awaiting supplier',s=>s.bucket==='Supplier'],procurement:['Awaiting procurement',s=>s.team==='Procurement'],ts:['Awaiting technical sales',s=>s.team==='Technical Sales'],supervisor:['Awaiting supervisor',s=>s.team==='Supervisor'||s.bucket==='Management'],blocked:['Blocked',s=>s.blocked],risk:['At risk',s=>s.atRisk]};
export async function loadWOs(u,{st='open',search=''}={}){
 await cal();const args=[],w=[];
 if(u.role==='tech'){args.push(u.id,u.team||'Technical');w.push('(w.created_by=$1 or exists(select 1 from tasks t where t.wo_id=w.id and (t.assignee=$1 or t.team=$2)) or exists(select 1 from subtasks s where s.wo_id=w.id and s.assignee=$1))')}
 if(st!=='all'){args.push(st);w.push(`w.status=$${args.length}`)}
 if(search){args.push('%'+search+'%');const n='$'+args.length;w.push(`(w.num ilike ${n} or w.client ilike ${n} or w.site ilike ${n} or w.ext_ref ilike ${n} or w.service ilike ${n} or exists(select 1 from tasks t where t.wo_id=w.id and (t.ref ilike ${n} or t.assignee_name ilike ${n} or t.team ilike ${n} or t.title ilike ${n})) or exists(select 1 from wo_assets x join assets a on a.id=x.asset_id where x.wo_id=w.id and (a.serial ilike ${n} or a.name ilike ${n})) or exists(select 1 from docs d where d.wo_id=w.id and d.num ilike ${n}))`)}
 const wos=await q(`select w.* from work_orders w ${w.length?'where '+w.join(' and '):''} order by w.created_at desc limit 500`,args);
 const ids=wos.map(x=>x.id),ts=wos.length?await q('select * from tasks where wo_id=any($1::int[]) order by seq',[ids]):[],subs=wos.length?await q('select id,task_id,wo_id,title,assignee_name,status,after from subtasks where wo_id=any($1::int[])',[ids]):[],now=Date.now();
 return wos.map(x=>({...x,S:summarize(x,ts.filter(t=>t.wo_id===x.id),now,subs.filter(s=>s.wo_id===x.id))}))}
