export const TEAMS={SM:'Sales & Marketing',TS:'Technical Sales',PR:'Procurement',TE:'Technical',SD:'Software Development',SU:'Support',SV:'Supervisor',MG:'Management'};
export const TEAM_LIST=Object.values(TEAMS);
const dm=s=>{const m=/^(\d+(?:\.\d+)?)(m|h|d)$/.exec((s||'').trim());return m?Math.round(+m[1]*{m:1,h:60,d:540}[m[2]]):null};
export function parse(dsl){
 const out=[],keys=new Set(),errs=[];
 dsl.split('\n').map(l=>l.trim()).filter(l=>l&&l[0]!=='#').forEach((l,i)=>{
  const [key,title,team,dur,deps='',fl='']=l.split('|').map(x=>x.trim()),f={};
  fl.split(';').filter(Boolean).forEach(x=>{const j=x.indexOf('=');j<0?f[x]=1:f[x.slice(0,j)]=x.slice(j+1)});
  const ds=deps?deps.split(',').map(x=>x.trim()):[],n=i+1;
  if(!key||!title)errs.push(`Line ${n}: key and title are required`);else if(keys.has(key))errs.push(`Line ${n}: duplicate key ${key}`);
  if(!TEAMS[team]&&!TEAM_LIST.includes(team))errs.push(`Line ${n}: unknown team “${team}”`);
  if(dm(dur)==null)errs.push(`Line ${n}: bad duration “${dur}” (use 30m, 6h, 2d)`);
  ds.forEach(d=>{if(!keys.has(d))errs.push(`Line ${n}: dependency “${d}” must be an earlier key`)});
  keys.add(key);
  out.push({key,title,team:TEAMS[team]||team,mins:dm(dur)||60,deps:ds,wait:f.wait||null,sub:f.sub||null,why:f.why||null,ev:f.ev?f.ev.split('+'):[],doc:f.doc||null,chk:f.chk||null,opt:!!f.opt,next:f.next||null})});
 if(errs.length)throw new Error(errs.join('\n'));return out}
export const critical=ts=>{const e={};let m=0;for(const t of ts){if(t.opt)continue;e[t.key]=t.mins+Math.max(0,...t.deps.map(k=>e[k]||0));m=Math.max(m,e[t.key])}return m};
const P='Identify supplier~Confirm availability~Raise PO/LPO~Supplier confirms~Await delivery or pickup';
const REQ='req|Initial Requirement Assessment|SM|4h||next=Record the client, site and requirement';
const SURVEY='survey|Conduct Site Survey|TE|6h|req|doc=sr:Site Survey;ev=doc;next=Complete the site survey document';
const SRC='proposal|Prepare Proposal|SM|6h|survey|ev=fileref;next=Attach the proposal or its external reference\nsourcing|Product Sourcing / Technical Procurement|TS|8h|proposal|ev=fileref;next=Record equipment, supplier, availability and lead time\nquote|Attach / Reference Technical Quotation|TS|1h|sourcing|ev=fileref;next=Attach the quotation or its external reference';
const APPR=d=>`approval|Obtain Client Approval|SM|2d|${d}|wait=Client;why=client approval;ev=fileref;next=Follow up with the client and attach the approval or LPO`;
const BUY='procure|Procure Approved Items|PR|2d|approval|ev=check+fileref;chk='+P+'\nreceive|Receive / Pick Up Materials|PR|1d|procure|wait=Supplier;why=supplier delivery;ev=check;chk=@items;next=List the required items and tick each as it is received';
const HAND=d=>`handover|Client Sign-off / Handover|TE|2h|${d}|doc=ho:;ev=signed;next=Have the client sign the handover`;
const L=(...a)=>a.join('\n');
export const SEED=[
['CCTV Installation','Installation',L(REQ,SURVEY,SRC,APPR('quote'),BUY,'install|Installation|TE|2d|receive,approval|doc=sr:Installation – CCTV;ev=check+doc;chk=Mount cameras~Run cabling~Install NVR~Configure network~Configure recording~Configure remote access~Label equipment','test|Testing|TE|4h|install|ev=check;chk=Camera views verified~Recording verified~Remote access verified',HAND('test'))],
['Biometric Installation','Installation',L(REQ,SURVEY,'design|Device / Door Assessment & Selection|TS|6h|survey|ev=fileref','sourcing|Product Sourcing|TS|8h|design|ev=fileref',APPR('sourcing'),BUY,'install|Installation|TE|2d|receive,approval|doc=sr:Installation – Biometric / Access Control;ev=doc','config|Configuration & Integration|TE|1d|install|ev=check;chk=Network settings~Access groups and schedules~Attendance / payroll integration','enrol|User Enrolment|TE|1d|config|ev=check;chk=Users enrolled~Enrolment verified','test|Testing|TE|4h|enrol|ev=check;chk=Each device tested~Fire release tested','train|Training|TE|2h|test',HAND('train'))],
['Access Control Installation','Installation',L(REQ,SURVEY,'design|Door & Reader Assessment|TS|6h|survey|ev=fileref','sourcing|Product Sourcing|TS|8h|design|ev=fileref',APPR('sourcing'),BUY,'install|Installation|TE|2d|receive,approval|doc=sr:Installation – Biometric / Access Control;ev=doc','config|Configuration|TE|1d|install|ev=check;chk=Controller settings~Access groups and schedules','test|Testing|TE|4h|config|ev=check;chk=Each door tested~Fire release tested',HAND('test'))],
['Network Installation','Installation',L(REQ,SURVEY,'design|Network Design|TE|6h|survey|ev=fileref','sourcing|Product Sourcing|TS|8h|design|ev=fileref',APPR('sourcing'),BUY,'install|Cabling & Installation|TE|3d|receive,approval|doc=sr:Installation – Network;ev=doc','config|Configuration|TE|1d|install|ev=check;chk=IP scheme and VLANs~Router and firewall~Wi-Fi','test|Testing|TE|4h|config|ev=check;chk=Cable certification~Throughput~Wi-Fi coverage',HAND('test'))],
['Hardware Deployment','Installation',L(REQ,'sourcing|Product Sourcing|TS|6h|req|ev=fileref',APPR('sourcing'),BUY,'install|Installation|TE|1d|receive,approval|doc=sr:Installation – Hardware;ev=doc','test|Testing|TE|2h|install|ev=check;chk=Devices power on~Connectivity verified',HAND('test'))],
['Preventive Maintenance','Maintenance',L('plan|Maintenance Job Generated & Scheduled|SV|1h||next=Confirm the schedule with the client','visit|Site Visit & Inspection|TE|3h|plan|doc=sr:Maintenance;ev=check;chk=Inspect equipment~Check connectivity~Check power / UPS','perform|Maintenance Performed|TE|3h|visit|ev=check;chk=Clean and update~Replace worn parts','test|Testing|TE|1h|perform','report|Report|TE|1h|test|ev=doc;next=Finish the site report','signoff|Client Sign-off|TE|1h|report|ev=signed;next=Have the client sign the report')],
['Break/Fix Maintenance','Maintenance',L('triage|Ticket Triage|SU|1h||next=Confirm the fault and priority','diag|Diagnosis (Site Visit / Remote)|TE|3h|triage|doc=wt:;ev=doc','parts|Parts Request|TE|1h|diag|opt;next=Only if parts are required','buy|Procure Parts|PR|1d|parts|opt;ev=fileref','recv|Receive Parts|PR|1d|buy|opt;wait=Supplier;why=parts delivery;ev=check;chk=@items','repair|Repair|TE|3h|diag,recv','test|Testing|TE|1h|repair','confirm|Client Confirmation|TE|1h|test|ev=signed;next=Have the client confirm and sign')],
['User Support','Support',L('triage|Triage & Prioritise|SU|30m||next=Set priority','remote|Remote Support / Diagnosis|SU|2h|triage|doc=wt:','escalate|Escalate to Specialist / Site Visit|SU|4h|remote|opt','resolve|Resolution|SU|2h|remote,escalate','confirm|User Confirmation|SU|1h|resolve|wait=Client;why=user confirmation;next=Ask the user to confirm the fix')],
['Biometric User Enrolment','Support',L('approval|Approval|SM|4h||next=Confirm the enrolment request is approved','details|User Details Received|SU|1d|approval|wait=Client;why=user details;ev=fileref','enrol|Enrolment|TE|2h|details|ev=check;chk=Users enrolled','verify|Verification|TE|1h|enrol','confirm|Confirmation|TE|1h|verify|wait=Client;why=client confirmation')],
['Software Development','Software',L('req|Requirement Gathering|SD|2d||ev=fileref','analysis|Requirement Analysis|SD|2d|req','scope|Scope Confirmation|SM|2d|analysis|wait=Client;why=scope confirmation;ev=fileref','design|Design (UI/UX, Database)|SD|3d|scope','dev|Development|SD|10d|design|sub=Backend~Frontend~API integration','review|Code Review|SD|1d|dev','test|Testing & Security Review|SD|3d|review|ev=check;chk=Functional tests~Security review','uat|User Acceptance Testing|SM|5d|test|wait=Client;why=UAT feedback;ev=fileref','fixes|Bug Fixes|SD|2d|uat|opt','deploy|Deployment|SD|1d|fixes,uat|ev=fileref;next=Attach the deployment record','train|Training|SD|1d|deploy','handover|Handover|SD|1d|train|ev=fileref','support|Post-Deployment Support|SU|5d|handover')],
['Software Enhancement','Software',L('analysis|Requirement Analysis|SD|1d','dev|Development|SD|4d|analysis','test|Testing|SD|1d|dev','uat|User Acceptance|SM|3d|test|wait=Client;why=UAT feedback','deploy|Deployment|SD|4h|uat|ev=fileref')],
['Software Bug','Software',L('triage|Bug Triage|SU|1h','fix|Fix|SD|1d|triage','test|Testing|SD|4h|fix','deploy|Deployment|SD|2h|test','confirm|Client Confirmation|SU|1d|deploy|wait=Client;why=client confirmation')],
['System Implementation','Software',L('req|Requirements|SD|1d','config|Configuration|SD|3d|req','migrate|Data Migration|SD|2d|config','test|Testing|SD|2d|migrate','uat|User Acceptance|SM|3d|test|wait=Client;why=UAT feedback','train|Training|SD|1d|uat','golive|Go-Live|SD|4h|train','handover|Handover|SD|4h|golive|ev=fileref')],
['Training','Training',L('req|Training Request & Requirement Assessment|SM|4h','plan|Training Plan|TE|4h|req|ev=fileref','trainer|Trainer Assignment|SV|1h|plan','prep|Materials Preparation|TE|1d|trainer|ev=fileref','confirm|Client Confirmation of Schedule|SM|2d|prep|wait=Client;why=schedule confirmation','session|Training Session|TE|1d|confirm','attend|Attendance Recorded|TE|1h|session|ev=fileref','feedback|Assessment / Feedback|TE|2h|attend','report|Completion Report|TE|2h|feedback|ev=fileref')],
['Consultancy','Consultancy',L('discover|Requirement Discovery|SM|1d','assess|Assessment|TE|2d|discover','research|Research & Technical Analysis|TE|3d|assess','recommend|Recommendations|TE|2d|research','deliver|Deliverable Preparation|TE|2d|recommend|ev=fileref','review|Client Review|SM|3d|deliver|wait=Client;why=client review','revise|Revision|TE|2d|review|opt','final|Final Delivery|TE|4h|review,revise|ev=fileref')]];
